/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Thai
 */
public class DangNhapForm extends javax.swing.JFrame {
    
    private static DangNhapForm INSTANCE = null;

    /**
     * Creates new form FormĐăngNhập
     */
    private DangNhapForm() {
        initComponents();
    }
    
    public static DangNhapForm getInstance(){
        if (INSTANCE == null) {
            INSTANCE = new DangNhapForm();
        }
        return INSTANCE;
    }
    
    public void buttonDangNhapActionPerformed(ActionListener l){
        buttonDangNhap.addActionListener(l);
    }

    public JPasswordField getTextMatKhau() {
        return textMatKhau;
    }

    public JTextField getTextTenDangNhap() {
        return textTenDangNhap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableDangNhap = new javax.swing.JLabel();
        textTenDangNhap = new javax.swing.JTextField();
        lableMatKhau = new javax.swing.JLabel();
        textMatKhau = new javax.swing.JPasswordField();
        buttonDangNhap = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(450, 300));

        lableDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableDangNhap.setText("Tên Đăng Nhập:");

        textTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTenDangNhap.setText("donvi1");

        lableMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableMatKhau.setText("Mật Khẩu:");

        textMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textMatKhau.setText("123");

        buttonDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDangNhap.setText("Đăng Nhập");

        buttonHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonHuy.setText("Hủy");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chương trình Quản lý thiết bị, vật tư");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lableDangNhap)
                        .addGap(19, 19, 19)
                        .addComponent(textTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(textMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonDangNhap)
                        .addGap(35, 35, 35)
                        .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableDangNhap)
                    .addComponent(textTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableMatKhau)
                    .addComponent(textMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDangNhap)
                    .addComponent(buttonHuy))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        buttonHuy.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDangNhap;
    private javax.swing.JButton buttonHuy;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lableDangNhap;
    private javax.swing.JLabel lableMatKhau;
    private javax.swing.JPasswordField textMatKhau;
    private javax.swing.JTextField textTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
