/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.ThietBi.ThemThietBiForm;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Thai
 */
public class MainForm extends javax.swing.JFrame {
    
    private static MainForm INSTANCE;
    
    /**
     * Creates new form TrangChu
     */
    private MainForm() {
        initComponents();
    }
    
    public static MainForm getInstance(){
        if (INSTANCE == null) {
            INSTANCE = new MainForm();
        }
        return INSTANCE;
    }
    
    /**
     * Tạo lắng nghe cho button Đăng xuất
     * @param l Sự kiện khi nhấn button
     */
    public void buttonDangXuatActionPerformed(ActionListener l){
        buttonDangXuat.addActionListener(l);
    }
    
    //===== Tạo lắng nghe ở ThemThietBiForm =====
    
    /**
     * Tạo lắng nghe cho button Thêm thiết bị
     * @param l Sự kiện lắng nghe 
     */
    public void buttonThemThietBiActionPerformed(ActionListener l){
        buttonThemThietBi.addActionListener(l);
    }
    
    /**
     * Tạo lắng nghe cho button Cập nhật thiết bị
     * @param l Sự kiện lắng nghe 
     */
    public void buttonCapNhatThietBiActionPerformed(ActionListener l){
        buttonCapNhatThietBi.addActionListener(l);
    }
    
    //===== Tạo lắng nghe ở CapNhatTieuThuVatTuForm =====
    
    /**
     * Tạo lắng nghe cho button Cập nhật
     * @param l Sự kiện lắng nghe
     */
    public void buttonCapNhatTieuThuVatTuActionPerformed(ActionListener l){
        buttonCapNhatTieuThuVatTu.addActionListener(l);
    }

    //===== getter và setter
    public JTabbedPane getTabbedPaneMain() {
        return tabbedPaneMain;
    }

    public JPanel getPanelQuanLyThietBi() {
        return panelQuanLyThietBi;
    }

    public JPanel getPanelQuanLyVatTu() {
        return panelQuanLyVatTu;
    }

    public JPanel getPanelThongKeThietBi() {
        return panelThongKeThietBi;
    }

    public JPanel getPanelThongKeVatTu() {
        return panelThongKeVatTu;
    }

    public JPanel getPanelYeuCauVatTu() {
        return panelYeuCauVatTu;
    }

    public JPanel getPanelCapNhatTieuThuVatTu() {
        return panelCapNhatTieuThuVatTu;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDangXuat = new javax.swing.JButton();
        buttonHuongDan = new javax.swing.JButton();
        lableTittle = new javax.swing.JLabel();
        tabbedPaneMain = new javax.swing.JTabbedPane();
        panelQuanLyThietBi = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonXemThietBi = new javax.swing.JButton();
        buttonThemThietBi = new javax.swing.JButton();
        buttonCapNhatThietBi = new javax.swing.JButton();
        buttonXoaThietBi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThietBi = new javax.swing.JTable();
        textTimThietBi = new javax.swing.JTextField();
        buttonTimThietBi = new javax.swing.JButton();
        panelQuanLyVatTu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonXemVatTu = new javax.swing.JButton();
        buttonThemVatTu = new javax.swing.JButton();
        buttonCapNhatVatTu = new javax.swing.JButton();
        buttonXoaVatTu = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableVatTu = new javax.swing.JTable();
        buttonTimVatTu = new javax.swing.JButton();
        textTimVatTu = new javax.swing.JTextField();
        panelThongKeThietBi = new javax.swing.JPanel();
        comboDonViThietBi = new javax.swing.JComboBox<>();
        lbDonVi = new javax.swing.JLabel();
        buttonThongKeThietBi = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableThongKeThietBi = new javax.swing.JTable();
        panelThongKeVatTu = new javax.swing.JPanel();
        buttonThongKeVatTu = new javax.swing.JButton();
        comboDonViVatTu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableThongKeVatTu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerThoiGianBatDau = new javax.swing.JSpinner();
        spinnerThoiGianKetThuc = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        panelYeuCauVatTu = new javax.swing.JPanel();
        lbDonVi1 = new javax.swing.JLabel();
        buttonYeuCauVatTu = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableYeuCau = new javax.swing.JTable();
        buttonYeuCauThietBi = new javax.swing.JButton();
        panelCapNhatTieuThuVatTu = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCapNhatTieuThuVatTu = new javax.swing.JTable();
        lbDonVi2 = new javax.swing.JLabel();
        buttonCapNhatTieuThuVatTu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Quản Lý Thiết Bị Vật Tư");
        setMinimumSize(new java.awt.Dimension(902, 664));
        setPreferredSize(new java.awt.Dimension(902, 664));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonDangXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDangXuat.setForeground(new java.awt.Color(153, 0, 51));
        buttonDangXuat.setText("Đăng Xuất");
        getContentPane().add(buttonDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 13, -1, -1));

        buttonHuongDan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonHuongDan.setText("Hướng Dẫn");
        getContentPane().add(buttonHuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 13, -1, -1));

        lableTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTittle.setForeground(new java.awt.Color(153, 0, 51));
        lableTittle.setText("Chương Trình Quản Lý Thiết Bị Vật Tư");
        getContentPane().add(lableTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, -1));

        tabbedPaneMain.setForeground(new java.awt.Color(51, 0, 102));
        tabbedPaneMain.setToolTipText("");
        tabbedPaneMain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        panelQuanLyThietBi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        buttonXemThietBi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonXemThietBi.setText("Xem Chi Tiết");

        buttonThemThietBi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonThemThietBi.setText("Thêm Thiết Bị");

        buttonCapNhatThietBi.setText("Cập Nhật");

        buttonXoaThietBi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonXoaThietBi.setText("Xóa Thiết Bị");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonCapNhatThietBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonThemThietBi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonXoaThietBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonXemThietBi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonThemThietBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonXemThietBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCapNhatThietBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonXoaThietBi)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        panelQuanLyThietBi.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 470));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Thiết Bị", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        tableThietBi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thiết Bị", "Tên Thiết Bị", "Số Lượng", "Ngày Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableThietBi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelQuanLyThietBi.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 39, 680, 470));
        jPanel5.getAccessibleContext().setAccessibleName("");

        panelQuanLyThietBi.add(textTimThietBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 147, -1));

        buttonTimThietBi.setText("Tìm kiếm");
        panelQuanLyThietBi.add(buttonTimThietBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        tabbedPaneMain.addTab("Quản Lý Thiết Bị", panelQuanLyThietBi);

        panelQuanLyVatTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        buttonXemVatTu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonXemVatTu.setText("Xem Chi Tiết");
        buttonXemVatTu.setMaximumSize(new java.awt.Dimension(167, 57));
        buttonXemVatTu.setMinimumSize(new java.awt.Dimension(167, 57));
        buttonXemVatTu.setPreferredSize(new java.awt.Dimension(167, 57));

        buttonThemVatTu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonThemVatTu.setText("Thêm Vật tư");

        buttonCapNhatVatTu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonCapNhatVatTu.setText("Cập Nhật");

        buttonXoaVatTu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonXoaVatTu.setText("Xóa Vật tư");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonXemVatTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonThemVatTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCapNhatVatTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonXoaVatTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonThemVatTu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonXemVatTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCapNhatVatTu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonXoaVatTu)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        panelQuanLyVatTu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 470));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Vật tư", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        tableVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableVatTu);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        panelQuanLyVatTu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 42, 690, 470));

        buttonTimVatTu.setText("Tìm kiếm");
        panelQuanLyVatTu.add(buttonTimVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));
        panelQuanLyVatTu.add(textTimVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 147, -1));

        tabbedPaneMain.addTab("Quản Lý Vật Tư", panelQuanLyVatTu);

        panelThongKeThietBi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboDonViThietBi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDonViThietBi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng kế toán", "Phòng nhân sự" }));
        panelThongKeThietBi.add(comboDonViThietBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 43, 150, 30));

        lbDonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDonVi.setText("Chọn đơn vị:");
        panelThongKeThietBi.add(lbDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        buttonThongKeThietBi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonThongKeThietBi.setText("Thống kê");
        panelThongKeThietBi.add(buttonThongKeThietBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, 150, 50));
        panelThongKeThietBi.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 150, 15));

        tableThongKeThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableThongKeThietBi);

        panelThongKeThietBi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 13, 710, 500));

        tabbedPaneMain.addTab("Thống kê thiết bị đơn vị", panelThongKeThietBi);

        panelThongKeVatTu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelThongKeVatTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonThongKeVatTu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonThongKeVatTu.setText("Thống kê");
        panelThongKeVatTu.add(buttonThongKeVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, 50));

        comboDonViVatTu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDonViVatTu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng kế toán", "Phòng nhân sự" }));
        panelThongKeVatTu.add(comboDonViVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chọn đơn vị:");
        panelThongKeVatTu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tableThongKeVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableThongKeVatTu);

        panelThongKeVatTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 720, 500));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Thời gian bắt đầu:");
        panelThongKeVatTu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thời gian kết thúc:");
        panelThongKeVatTu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        spinnerThoiGianBatDau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerThoiGianBatDau.setModel(new javax.swing.SpinnerDateModel());
        panelThongKeVatTu.add(spinnerThoiGianBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        spinnerThoiGianKetThuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerThoiGianKetThuc.setModel(new javax.swing.SpinnerDateModel());
        panelThongKeVatTu.add(spinnerThoiGianKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));
        panelThongKeVatTu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 10));

        tabbedPaneMain.addTab("Thống kê sử dung vật tư", panelThongKeVatTu);

        panelYeuCauVatTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDonVi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDonVi1.setText("Các Thiết bị/Vật tư đã yêu cầu:");
        panelYeuCauVatTu.add(lbDonVi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        buttonYeuCauVatTu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonYeuCauVatTu.setText("Yêu cầu Vật tư");
        panelYeuCauVatTu.add(buttonYeuCauVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 70));

        tableYeuCau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên thiết bị/Vật tư", "Số lượng", "Đơn vị tính", "Thông số kỹ thuật", "Thời gian cần cấp"
            }
        ));
        jScrollPane5.setViewportView(tableYeuCau);

        panelYeuCauVatTu.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 33, 710, 480));

        buttonYeuCauThietBi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonYeuCauThietBi.setText("Yêu cầu Thiết bị");
        panelYeuCauVatTu.add(buttonYeuCauThietBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, 150, 70));

        tabbedPaneMain.addTab("Yêu cầu sử dụng", panelYeuCauVatTu);

        panelCapNhatTieuThuVatTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCapNhatTieuThuVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Vật tư", "Số lượng", "Đơn vị tính", "Thông số kỹ thuật", "Thời gian cần cấp"
            }
        ));
        jScrollPane6.setViewportView(tableCapNhatTieuThuVatTu);

        panelCapNhatTieuThuVatTu.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 33, 710, 480));

        lbDonVi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDonVi2.setText("Các vật tư hiện có:");
        panelCapNhatTieuThuVatTu.add(lbDonVi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        buttonCapNhatTieuThuVatTu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCapNhatTieuThuVatTu.setText("Cập nhật");
        panelCapNhatTieuThuVatTu.add(buttonCapNhatTieuThuVatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 70));

        tabbedPaneMain.addTab("Cập nhật tiêu thụ vật tư", panelCapNhatTieuThuVatTu);

        getContentPane().add(tabbedPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm main = new MainForm();
                main.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCapNhatThietBi;
    private javax.swing.JButton buttonCapNhatTieuThuVatTu;
    private javax.swing.JButton buttonCapNhatVatTu;
    private javax.swing.JButton buttonDangXuat;
    private javax.swing.JButton buttonHuongDan;
    private javax.swing.JButton buttonThemThietBi;
    private javax.swing.JButton buttonThemVatTu;
    private javax.swing.JButton buttonThongKeThietBi;
    private javax.swing.JButton buttonThongKeVatTu;
    private javax.swing.JButton buttonTimThietBi;
    private javax.swing.JButton buttonTimVatTu;
    private javax.swing.JButton buttonXemThietBi;
    private javax.swing.JButton buttonXemVatTu;
    private javax.swing.JButton buttonXoaThietBi;
    private javax.swing.JButton buttonXoaVatTu;
    private javax.swing.JButton buttonYeuCauThietBi;
    private javax.swing.JButton buttonYeuCauVatTu;
    private javax.swing.JComboBox<String> comboDonViThietBi;
    private javax.swing.JComboBox<String> comboDonViVatTu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lableTittle;
    private javax.swing.JLabel lbDonVi;
    private javax.swing.JLabel lbDonVi1;
    private javax.swing.JLabel lbDonVi2;
    private javax.swing.JPanel panelCapNhatTieuThuVatTu;
    private javax.swing.JPanel panelQuanLyThietBi;
    private javax.swing.JPanel panelQuanLyVatTu;
    private javax.swing.JPanel panelThongKeThietBi;
    private javax.swing.JPanel panelThongKeVatTu;
    private javax.swing.JPanel panelYeuCauVatTu;
    private javax.swing.JSpinner spinnerThoiGianBatDau;
    private javax.swing.JSpinner spinnerThoiGianKetThuc;
    private javax.swing.JTabbedPane tabbedPaneMain;
    private javax.swing.JTable tableCapNhatTieuThuVatTu;
    private javax.swing.JTable tableThietBi;
    private javax.swing.JTable tableThongKeThietBi;
    private javax.swing.JTable tableThongKeVatTu;
    private javax.swing.JTable tableVatTu;
    private javax.swing.JTable tableYeuCau;
    private javax.swing.JTextField textTimThietBi;
    private javax.swing.JTextField textTimVatTu;
    // End of variables declaration//GEN-END:variables
}
